//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public System.Guid Id { get; set; }
        public string Address1 { get; set; }
        public System.Guid Region2ProvinceId { get; set; }
        public string PostalCode { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        public virtual Region2Province Region2Province { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}
