//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.PictureLibraries = new HashSet<PictureLibrary>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public string ContentType { get; set; }
        public byte[] Content { get; set; }
    
        public virtual ICollection<PictureLibrary> PictureLibraries { get; set; }
    }
}
