//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureLibrary
    {
        public PictureLibrary()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid PictureId { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}
