//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalUser
    {
        public PortalUser()
        {
            this.Properties = new HashSet<Property>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
