//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Region2Province = new HashSet<Region2Province>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual ICollection<Region2Province> Region2Province { get; set; }
    }
}
