//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region2Province
    {
        public Region2Province()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid RegionId { get; set; }
        public System.Guid ProvinceId { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Province Province { get; set; }
        public virtual Region Region { get; set; }
    }
}
