//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.Availabilities = new HashSet<Availability>();
        }
    
        public System.Guid Id { get; set; }
        public string UserEmail { get; set; }
        public System.Guid PortalUserId { get; set; }
        public bool IsConfirmed { get; set; }
        public string Message { get; set; }
    
        public virtual ICollection<Availability> Availabilities { get; set; }
        public virtual PortalUser PortalUser { get; set; }
    }
}
